version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - DEV_DATABASE_URL=postgresql://postgres:postgres@db:5432/url_shortener
    volumes:
      - ..:/app
    depends_on:
      - db
    restart: unless-stopped
    command: flask run --host=0.0.0.0

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"

volumes:
  postgres_data:
